version: '3.9'

services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb

  spa:
    build:
      context: js
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - spa_volume:/data
    depends_on:
      - api
    links:
      - api

  sidekiq_indexer:
    build: .
    command: bundle exec sidekiq -C config/sidekiq/indexer.yml
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  sidekiq_cron:
    build: .
    command: bundle exec sidekiq -C config/sidekiq/cron.yml
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  mongodb:
    image: mongo:4.4.5
    volumes:
      - mongodb_volume:/data

  redis:
    image: redis:5.0.8
    restart: always
    volumes:
      - redis_volume:/data

volumes:
  mongodb_volume:
  redis_volume:
  spa_volume:
